### ISSUE TITLE
Data Request-  Research Student MS Operations Research

### ISSUE THREAD

**Issue by auroregosmant** [tlamadon/blm-replicate#4]
Dear Thibaut Lamadon, I am a current research student in MS Operations Research, and find your work extremely interesting. Because I am working on an Econometrics project which topic include many aspects similar to the work you did, I would love to have access to data, and be able to run your code on it. Would it be possible for you to provide me with the access to it, as I already sent a mail to IFAU to request data, but am still waiting a response from them?

Many thanks,

**Comment by tlamadon** [comment]
Hi there, sorry to hear this. Getting access to the data is cumbersome. Because it is confidential it requires quite a strict vetting. That being said such matched data is available from several countries: France, Denmark, Spain, Italy. I can only recommend trying to get access to any of these. Sorry this is hard in practice.
